name: "Kern Lab"
description: "This is the official web page for Dorothee Kern's lab at the Scripps Research Institute in San Diego."

url: "https://kernlab-scripps.github.io"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

defaults:
  -
    scope:
      path: "/static/*"
    values:
      sitemap: false
